services:
  - type: web
    name: roleta-css-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget gnupg unzip curl && \
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
      apt install -y ./google-chrome-stable_current_amd64.deb && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py
