services:
  - type: web
    name: roleta-css-detector
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip gnupg curl && \
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
      apt install -y ./google-chrome-stable_current_amd64.deb && \
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+') && \
      CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | grep -A 10 $CHROME_VERSION | grep "linux64" | grep -oP 'https://[^"]+') && \
      curl -o chromedriver.zip $CHROMEDRIVER_VERSION && \
      unzip chromedriver.zip && \
      mv chromedriver-linux64/chromedriver /usr/bin/chromedriver && \
      chmod +x /usr/bin/chromedriver && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py
